import classes from './Header.module.css'
import Nav from 'components/ui/Nav/Nav'
import Head from 'next/head'
import Link from 'next/link'
import BarreRecherche from '../barreRecherche/BarreRecherche'
import Image from 'next/dist/client/image'
import scan from 'public/qrcode.png'
import IsConnected from 'lib/isConnected'

export default function Header (): JSX.Element {
  return (
    <>
      <Head>
        <title>Mon zoo à moi</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      {IsConnected() && (
        <Link href='/scan'>
          <Image
            src={scan}
            alt='scan'
            width={50}
            height={50}
            className={classes.logo_scan}
          />
        </Link>
      )}
      <header className={classes.Header}>
        <div
          className='containerH'
          style={{
            justifyContent: 'space-between'
          }}
        >
          <h1 style={{ margin: 0 }}>
            <Link href='/'>Mon Zoo à moi !</Link>
          </h1>
          <Nav />
          <BarreRecherche />
        </div>
      </header>
    </>
  )
}
